name: devmob_gestion_taches
description: Application de gestion de projets et tÃ¢ches collaboratives
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core
  firebase_core: ^3.0.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0

  # Security
  flutter_secure_storage: ^9.0.0

  # Image picker (avatar)
  image_picker: ^1.1.0

  # Kanban drag & drop
  flutter_drag_and_drop: ^0.3.0
  drag_and_drop_lists: ^2.3.0

  # Notifications
  flutter_local_notifications: ^17.0.0
  firebase_messaging: ^15.0.0

  # Charts (progression + dashboard)
  fl_chart: ^0.65.0
  percent_indicator: ^4.2.3

  # Calendriers / deadlines
  table_calendar: ^3.1.1
  syncfusion_flutter_calendar: ^28.2.0

  # State management (Provider)
  provider: ^6.1.2

  # HTTP (optional external API)
  http: ^1.2.1

  # Utils
  intl: ^0.19.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  bloc_test: ^9.1.3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
