name: projetflutter_ds
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^3.7.0

  # Firebase Auth
  firebase_auth: ^5.4.0

  # Cloud Firestore
  cloud_firestore: ^5.4.1

  # Provider 
  provider: ^6.1.2

 #UI
  google_fonts: ^6.2.0
  flutter_spinkit: ^5.2.1
  intl: ^0.19.0

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

 
